media_layout:
  image_1: "https://www.luxstay.com/account/coins@2x.png"
  image_2: "https://www.luxstay.com/account/top-sales@2x.png"
  image_3: "https://www.luxstay.com/account/wallet@2x.png"
  image_4: "https://www.luxstay.com/account/backpack@2x.png"
omiauth:
  facebook: "https://cdn6.agoda.net/images/universal-login/facebook-logo.svg"
  google: "https://cdn6.agoda.net/images/universal-login/google-logo-v2.svg"
banner:
  image_1: "https://beta-api.luxstay.net/api/upload/file?storage=admins/12/PEolFdE3k1ptD46IuWloWvph.jpg"
  image_2: "https://beta-api.luxstay.net/api/upload/file?storage=admins/12/H8cBLcwZmm0cYe5GnvSKCHCI.jpg"
  image_3: "https://beta-api.luxstay.net/api/upload/file?storage=admins/12/qF7ukmI--Rwr2H5LwzVZwcXa.jpg"
paginate: 4
room_model:
  name_max: 80
  des_max: 250
valid:
  city:
    name:
      length: 100
homepage:
  get_city: 5
